language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
deploy:
  provider: releases
  api_key:
    secure: lzIGGqd8/D/RMYhlUk50Uird6jwvXktxA2AXpGy2aahhczhoQJbQtsTKKZstvW6Pb4S3jzOhNBpfwneNpy+WgwKGjRrJ1pNW7qd5N7dlYOF51HeM2XhSu/JoJraC5kqsvbdR2tY97Q9FTYKWR+2mAOmIkxDfFE/zTdQvfmdOm4GaP3q8HX9bugPPgf6/hiJ15FifL6UKcXwsf4YXXNemhoIwc6vfsVaQYtvP8QhWPxXqAp4F93eZ/SRMuDFIPywzsM4mo0ANsDD6wIXBq4MCKUJAVNguTzESrhv+TGN2ZhWudnsL/QgaPYU1ii8oRHOirV6O/uEIUQvxYRoPq1rxJzxrRBkq6w3N9ZsUDQujeNmSmfHkynvPC6PfH1InD38WxkPj0upGna+iboNJYIKRM2h1ht/vyCq7HRLq9w+pGq2693LQR/YPBDQCQQ0KjoXn9m96nasDHXn6YeipKC3BQV2BMMds+QvDHTvlQ56DhJgMk2JsZqpvW6JtSQ6IOnDwtAE+2dYRuOes0ZcwsPqpaSvhiz2QtWnd5ipYzo1z23MM4l+VWWzd2hCLFBJHAfs0ncRDzpHcZVpneO8HuohGclDmr3YFzelnD4XjX4RkkN0Xld15Zt+DwzSiRJr6+M/i4Fb6s05Wc59V0LYN8SsidcsnHLdUoiWRqDFnsACfN4s=
  file: build/libs/tracey-rabbitmq-neo4j-bridge.jar
  skip_cleanup: true
  on:
    tags: true
